### PR TITLE
initial dpul svg idea

### PR DESCRIPTION
**Pull request by jpstroop**
I made this a few weeks ago and pushed up the branch but forgot to make a PR. It's for Plum and Pom, and is essentially a squared of version of the library logo.

### CODE REVIEW

**Comment by sdellis** [comment]
@jpstroop This logomark already exists in the identity sheet.  I pulled it out and added it here.  I will convert this identity sheet to svg rather than illustrator since I'm not sure you can import it into other svg drawing tools.  At any rate, the concept you posted lacks the bezier curves that emphasize the allusion to an "open book" in the bottom of the logomark, so I suggest using the "official" one.

**Comment by jpstroop** [comment]
Right, the curves are what I was trying to get rid of as a subtle variation for "Digital PUL" (Henry playing minecraft at the time is where I got the idea). I basically took the original image and added guides at the edges and then filled them out:

image

I enhanced the peak of the book page a little bit because the angles weren't dramatic enough to be clear, imo. I also used Princeton orange (`#e87722` / `rgb(232,119,34)` / PMS 158), which I think the library should be working toward, but can change it if we want to stay w/ Pumpkin (`#f58026`, `rgb(245,128,38)`). I'm no artist and totally open to something else.

**Comment by sdellis** [comment]
Sorry, I misunderstood!  Carry on...

**Comment by jpstroop** [comment]
I'm completely open to other ideas, seriously, we just need something and I'd prefer it not stray too far.

**Pull request merged**
